package com.example.faceguard.model.permission;

public enum Permission {
    ADD_ROLE, UPDATE_ROLE, DELETE_ROLE, READ_ROLE,
    ADD_USER, UPDATE_USER, DELETE_USER, READ_USER,
    ADD_COMPANY, UPDATE_COMPANY, DELETE_COMPANY, READ_COMPANY,
    ADD_BRANCH, UPDATE_BRANCH, DELETE_BRANCH, READ_BRANCH,
    ADD_DEPARTMENT, UPDATE_DEPARTMENT, DELETE_DEPARTMENT, READ_DEPARTMENT,
}
