package com.example.faceguard.model.permission;

public enum Permission {
    CREATE_ROLE, UPDATE_ROLE, DELETE_ROLE, READ_ROLE,
    CREATE_USER, UPDATE_USER, DELETE_USER, READ_USER,
    CREATE_COMPANY, UPDATE_COMPANY, DELETE_COMPANY, READ_COMPANY,
    CREATE_BRANCH, UPDATE_BRANCH, DELETE_BRANCH, READ_BRANCH,
    CREATE_DEPARTMENT, UPDATE_DEPARTMENT, DELETE_DEPARTMENT, READ_DEPARTMENT,
}
